name: "publish"

on:
  push:
    branches:
      - "main"
      - "master"
    paths:
      - src/**
      - build.gradle
      - gradle.properties
      - settings.gradle
  workflow_dispatch:

env:
  RELEASE_TITLE: "World Preview 1.15.2 build ${{github.run_number}}"
  RELEASE_NUMBER: "${{github.run_number}}"
  RELEASE_FILE: "build/libs/*${{github.run_number}}.0.0.jar"

jobs:
  publish:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build artifacts
        run: ./gradlew build
      - name: Publish tagged version
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "v${{ env.RELEASE_NUMBER }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: ${{ env.RELEASE_TITLE }}
          files: |
            LICENSE*
            ${{ env.RELEASE_FILE }}
      - name: Publish latest
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: ${{ env.RELEASE_TITLE }}
          files: |
            LICENSE*
            ${{ env.RELEASE_FILE }}
